nodejs:
  image: 'hmctspublic.azurecr.io/sscs/tribunals-frontend:latest'
  applicationPort: 3000
  aadIdentityName: sscs
  livenessPath: /health/readiness
  environment:
    NODE_ENV: "production"
    TRIBUNALS_CASE_API_URL: http://sscs-tribunals-api-pr-2078.service.core-compute-preview.internal
    UPLOAD_EVIDENCE_URL: http://sscs-tribunals-api-pr-2078.service.core-compute-preview.internal/evidence/upload
    SERVICES_IDAM_LOGIN_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net/login
    SERVICES_IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net

    # seems to be disabled currently and only enabled locally pointing at AAT
    # SERVICES_WEB_FORM:

    # This is currently disabled in prod, enabled all other environments
    CONTACT_US_WEB_FORM_ENABLED: false
    MEDIA_FILES_ALLOWED_ENABLED: true

    # these are only enabled in prod
    # SERVICES_WEBCHAT_UUID:
    # SERVICES_WEBCHAT_TENANT
    # SERVICES_WEBCHAT_CHANNEL
    # SERVICES_BTN_NO_AGENTS
    # SERVICES_BTN_AGENTS_BUSY
    # SERVICES_BTN_SERVICE_CLOSED

    POSTCODE_CHECKER_ALLOWED_RPCS: "birmingham,liverpool,sutton,leeds,newcastle,cardiff,glasgow,bradford"
    UV_THREADPOOL_SIZE: 64
    FT_ANTENNA_WEBCHAT: false
    FT_WELSH: true
    ALLOW_DLA_ENABLED: true

  keyVaults:
    sscs:
      secrets:
        - idam-sscs-oauth2-client-secret
        - postcode-lookup-token
        - sscs-redis-access-key
        - sscs-redis-connection-string
        - AppInsightsInstrumentationKey
        - pcq-token-key

redis:
  enabled: false
  cluster:
    enabled: false
    slaveCount: 0
  usePassword: false
  master:
    persistence:
      enabled: false

idam-pr:
  enabled: false
