nodejs:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    NODE_ENV: "aat"
    #Added for new Webchat with Agent
    WELSH_WEBCHAT_ENABLED: true
    WEBCHAT_URL: "webchat.pp.ctsc.hmcts.net"
    WEBCHAT_CLIENT_URL: "webchat-client.pp.ctsc.hmcts.net"
    PCQ_URL: "https://pcq.aat.platform.hmcts.net"
    FT_WELSH: true
    PCQ_ENABLED: true
    WEBCHAT_OPENING_TIME_8_5: true
    IBC_NI_POSTCODES_FEATURE: true
    KERV_WEBCHAT_ENABLED: false

